---
name: "Tests"

on:  # yamllint disable-line rule:truthy
  push:
    branches:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: full

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.74
          override: true
          components: rustfmt, clippy
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

  cargo-build:
    name: "cargo build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.74
          override: true
      - uses: Swatinem/rust-cache@v1
      - run: cargo build --all

  helloworld-example:
    name: "helloworld example"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.74
          override: true
      - uses: Swatinem/rust-cache@v1
      - run: cd examples/helloworld/ && cargo build && ./target/debug/helloworld

  keyvalue-example:
    name: "keyvalue example"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.74
          override: true
      - uses: Swatinem/rust-cache@v1
      - run: cd examples/keyvalue/ && cargo build && ./target/debug/keyvalue

  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v2
      - name: Spell Check
        uses: crate-ci/typos@master
        with:
          files: ./src
